const List<String> allPrompts = [
    "Describe a moment today that made you smile.",
    "If you could talk to your future self, what would you say?",
    "What is a challenge you overcame recently?",
    "Describe your perfect morning.",
    "What is a song that describes your mood right now?",
    "Write about a person who inspires you.",
    "What is something you want to learn?",
    "Describe a place where you feel most at peace.",
    "What is a small act of kindness you witnessed or performed?",
    "If you could change one thing about today, what would it be?",
    "What are three things you love about yourself?",
    "Describe a vivid dream you remember.",
    "What is a book or movie that changed your perspective?",
    "Write a letter to someone you miss.",
    "What is your favorite childhood memory?",
    "If you had a superpower, what would it be and why?",
    "What is a goal you are working towards?",
    "Describe the weather today and how it makes you feel.",
    "What is something you are looking forward to?",
    "Write about a mistake you made and what you learned from it.",
    "What is your favorite comfort food?",
    "If you could travel anywhere, where would you go?",
    "What is a habit you want to break or start?",
    "Describe a color that represents your day.",
    "What is the best advice you've ever received?",
    "Who made a positive impact on your life recently?",
    "What is something you take for granted?",
    "Describe a sound that you find relaxing.",
    "If you could have dinner with anyone, living or dead, who would it be?",
    "What is a quote that resonates with you right now?",
];